### ISSUE TITLE
Bug: check for stretched grid breaks running with minimal graph config

### ISSUE THREAD

**Issue by dietervdb-meteo** [ecmwf/anemoi-training#203]
### What happened?

The merging of [PR199](https://github.com/ecmwf/anemoi-training/pull/199/files) introduced the line
`if "lam_resolution" in getattr(config.graph.nodes.hidden, "node_builder", []):` in forecaster.py
This will result in an error in case one sets up a config where the graph part is the minimal
```yaml
graph:
  overwrite: False 
  data: data
  hidden: hidden
```
which is sufficient to load a graph previously stored on disk. Rather than trying to determine if the model is stretched grid or not from the graph part of the training config this should preferably be checked on the graph directly.

### What are the steps to reproduce the bug?

Run training with a config for which the graph part is as above.

### Version

current develop

### Platform (OS and architecture)

Lumi [irrelevant]

### Organisation

rmi

**Comment by dietervdb-meteo** [comment]
@jswijnands , any simple fixes/ways around for this?

**Comment by dietervdb-meteo** [comment]
As a temporary fix, the following minimal graph config still works [when running from a graph on disk]:
```yaml
graph:
  overwrite: False #This to take graph from file
  data: data #This and next line needed by AnemoiModelEncProcDec in anemoi-models
  hidden: hidden 
  # below needed to circumvent the bug reported here [it doesn't do anything else in the code]
  nodes:
    hidden:
      node_builder:
        _target_: anemoi.graphs.nodes.LimitedAreaTriNodes # options: ZarrDatasetNodes, NPZFileNodes, TriNodes
```
