### ISSUE TITLE
Able to finish training with one GPU, but got ERROR with "num_gpus_per_node: 2"

### ISSUE THREAD

**Issue by mixty1101** [ecmwf/anemoi-training#80]
### What happened?

After revising ‘num_gpus_per_node’ from 1 to 2 in the debug.yml and run "anemoi-training train --config-name=debug.yaml", I got the error below.

here's my debug.yml

```
defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: eval_rollout
- hardware: example
- graph: multi_scale
- model: gnn
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  plot:
    enabled: False
hardware:
  num_gpus_per_node: -1
  #num_nodes: 1
  #num_gpus_per_model: 2
  paths:
    data: /home/sprixin/test/anemoi
    output: /home/sprixin/test/anemoi/outputs/
    checkpoints: ${hardware.paths.output}checkpoint/
  files:
    dataset: dataset.zarr
    checkpoint:
      every_n_epochs: anemoi-by_epoch-epoch_{epoch:03d}-step_{step:06d}
      every_n_train_steps: anemoi-by_step-epoch_{epoch:03d}-step_{step:06d}
      every_n_minutes: anemoi-by_time-epoch_{epoch:03d}-step_{step:06d}
    warm_start: null
    # graph: ???
  # num_gpus_per_node: 2
  # num_nodes: 1
  # num_gpus_per_model: 1
model:
  num_channels: 128
dataloader:
  limit_batches:
    training: 100
    validation: 100
training:
  max_epochs: 5
```

configuration: 4090*2;  ubuntu 22.04; 
python env: mainly following anemoi documentation

### What are the steps to reproduce the bug?

following the anemoi documentation do the training
`anemoi-training train` to generate  debug.yaml and etc.
successful do the first training with debug.yaml(num_gpus_per_node: 1)
get error when changing num_gpus_per_node from 1 to 2

### Version

develop

### Platform (OS and architecture)

ubuntu22

### Relevant log output

```shell
...
usage: anemoi-training [-h] [--version] [--debug] {checkpoint,config,mlflow,train} ...
anemoi-training: error: argument command: invalid choice: 'hydra.run.dir="outputs/2024-10-10/11-02-12"' (choose from 'checkpoint', 'config', 'mlflow', 'train')
[2024-10-10 11:02:24,571][lightning_fabric.utilities.distributed][INFO] - Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
[2024-10-10 11:02:29,494][lightning_fabric.strategies.launchers.subprocess_script][INFO] - [rank: 1] Child process with PID 629502 terminated with code 2. Forcefully terminating all other processes to avoid zombies 🧟
Killed
```
